# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  cyclop:
    max-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true
  funlen:
    lines: 80

linters:
  enable-all: true
  disable:
    - lll
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - forcetypeassert
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - testpackage
    - exhaustruct
    - rowserrcheck # disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - sqlclosecheck # disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - wastedassign # disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - tagalign
    - depguard
    - err113
    - mnd
    - execinquery # deprecated
    - exportloopref # deprecated
    - tenv # can't be used in with t.Parallel()

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
        - dupl
      path: "_test.go"

