// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GeolocationDataReader is an autogenerated mock type for the GeolocationDataReader type
type GeolocationDataReader struct {
	mock.Mock
}

type GeolocationDataReader_Expecter struct {
	mock *mock.Mock
}

func (_m *GeolocationDataReader) EXPECT() *GeolocationDataReader_Expecter {
	return &GeolocationDataReader_Expecter{mock: &_m.Mock}
}

// ReadGeolocationData provides a mock function with given fields: ctx
func (_m *GeolocationDataReader) ReadGeolocationData(ctx context.Context) (<-chan []string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadGeolocationData")
	}

	var r0 <-chan []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan []string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeolocationDataReader_ReadGeolocationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadGeolocationData'
type GeolocationDataReader_ReadGeolocationData_Call struct {
	*mock.Call
}

// ReadGeolocationData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GeolocationDataReader_Expecter) ReadGeolocationData(ctx interface{}) *GeolocationDataReader_ReadGeolocationData_Call {
	return &GeolocationDataReader_ReadGeolocationData_Call{Call: _e.mock.On("ReadGeolocationData", ctx)}
}

func (_c *GeolocationDataReader_ReadGeolocationData_Call) Run(run func(ctx context.Context)) *GeolocationDataReader_ReadGeolocationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GeolocationDataReader_ReadGeolocationData_Call) Return(_a0 <-chan []string, _a1 error) *GeolocationDataReader_ReadGeolocationData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeolocationDataReader_ReadGeolocationData_Call) RunAndReturn(run func(context.Context) (<-chan []string, error)) *GeolocationDataReader_ReadGeolocationData_Call {
	_c.Call.Return(run)
	return _c
}

// NewGeolocationDataReader creates a new instance of GeolocationDataReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeolocationDataReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeolocationDataReader {
	mock := &GeolocationDataReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
