// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VioService_GeolocationByIPExposer_FullMethodName = "/api.vio.VioService/GeolocationByIPExposer"
)

// VioServiceClient is the client API for VioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The API Vio manage geolocation data.
type VioServiceClient interface {
	// GeolocationByIPExposer expose the geolocation data by IP.
	//
	// Receives a request with the ip. Responses with the geolocation data otherwise not.
	GeolocationByIPExposer(ctx context.Context, in *GeolocationByIPExposerRequest, opts ...grpc.CallOption) (*GeolocationByIPExposerResponse, error)
}

type vioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVioServiceClient(cc grpc.ClientConnInterface) VioServiceClient {
	return &vioServiceClient{cc}
}

func (c *vioServiceClient) GeolocationByIPExposer(ctx context.Context, in *GeolocationByIPExposerRequest, opts ...grpc.CallOption) (*GeolocationByIPExposerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeolocationByIPExposerResponse)
	err := c.cc.Invoke(ctx, VioService_GeolocationByIPExposer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VioServiceServer is the server API for VioService service.
// All implementations must embed UnimplementedVioServiceServer
// for forward compatibility.
//
// The API Vio manage geolocation data.
type VioServiceServer interface {
	// GeolocationByIPExposer expose the geolocation data by IP.
	//
	// Receives a request with the ip. Responses with the geolocation data otherwise not.
	GeolocationByIPExposer(context.Context, *GeolocationByIPExposerRequest) (*GeolocationByIPExposerResponse, error)
	mustEmbedUnimplementedVioServiceServer()
}

// UnimplementedVioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVioServiceServer struct{}

func (UnimplementedVioServiceServer) GeolocationByIPExposer(context.Context, *GeolocationByIPExposerRequest) (*GeolocationByIPExposerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeolocationByIPExposer not implemented")
}
func (UnimplementedVioServiceServer) mustEmbedUnimplementedVioServiceServer() {}
func (UnimplementedVioServiceServer) testEmbeddedByValue()                    {}

// UnsafeVioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VioServiceServer will
// result in compilation errors.
type UnsafeVioServiceServer interface {
	mustEmbedUnimplementedVioServiceServer()
}

func RegisterVioServiceServer(s grpc.ServiceRegistrar, srv VioServiceServer) {
	// If the following call pancis, it indicates UnimplementedVioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VioService_ServiceDesc, srv)
}

func _VioService_GeolocationByIPExposer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeolocationByIPExposerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VioServiceServer).GeolocationByIPExposer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VioService_GeolocationByIPExposer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VioServiceServer).GeolocationByIPExposer(ctx, req.(*GeolocationByIPExposerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VioService_ServiceDesc is the grpc.ServiceDesc for VioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.vio.VioService",
	HandlerType: (*VioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeolocationByIPExposer",
			Handler:    _VioService_GeolocationByIPExposer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
